name: Build and Run ImGui Example on Linux

on: [push, workflow_dispatch]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :0
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake libglfw3-dev xvfb imagemagick

    - name: Clone ImGui repository
      run: git clone https://github.com/ocornut/imgui.git

    - name: Build example
      run: |
        cd imgui/examples/example_glfw_opengl3
        make
        
    - name: Run xvfb and start imgui app
      run: |
        set -x
        
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
        
        # start xvfb on (default) display :0
        sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &
        
    - name: start imgui app
      run: |
        set -x
        
        cd imgui/examples/example_glfw_opengl3
        ./example_glfw_opengl3 &
        
        sleep 5
        
        import -window root screenshot.png
        

    - name: Upload screenshot artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: screenshot.png
