name: Build and Run ImGui Example on Linux

on: [push, workflow_dispatch]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake libglfw3-dev xvfb imagemagick

    - name: Clone ImGui repository
      run: git clone https://github.com/ocornut/imgui.git

    - name: Build example
      run: |
        cd imgui/examples/example_glfw_opengl3
        make

    - name: Run example and take screenshot
      run: |
        export DISPLAY=:99
        xvfb-run -a ./build/example_glfw_opengl3/example_glfw_opengl3 &
        sleep 5
        import -window root screenshot.png

    - name: Upload screenshot artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshot
        path: screenshot.png
