name: Build and Run ImGui Example on Linux

on: [push, workflow_dispatch]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    env:
      DISPLAY: :1
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake libglfw3-dev xvfb imagemagick

    - name: Clone ImGui repository
      run: git clone https://github.com/ocornut/imgui.git

    - name: Build example
      run: |
        cd imgui/examples/example_glfw_opengl3
        make
        
    - name: Run xvfb and start imgui app
      run: |
        set -x
        
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
        
        Xvfb $DISPLAY &
        sleep 10
        
    - name: start imgui app
      run: |
        set -x
        
        ./imgui/examples/example_glfw_opengl3/example_glfw_opengl3 &
        
        sleep 10
        
        import -pause 1 -window root screenshot.jpg
        
        killall example_glfw_opengl3
        killall Xvfb
        

    - name: Upload screenshot artifact
      uses: actions/upload-artifact@v2
      with:
        name: screenshot.jpg
        path: screenshot.jpg
